theme: jekyll-theme-minimal
title: Roxalis
description:
author: Patrick Thunder
logo: assets/images/lovedeath.jpg
url: https://roxalis.github.io
google_analytics: UA-147396279-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

footer-links:
  email: roxalis@runbox.com
  github: roxalis
  linkedin:
  twitter: roxalisgh
