theme: jekyll-theme-minimal
title: Roxalis
description:
author: POB
logo: assets/images/Oxalis.jpg
url: https://roxalis.github.io
google_analytics:

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

footer-links:
  email: test@runbox.com
  github: roxalis
  linkedin: test
  twitter: test
